// src/mailer/mailer.ts
import nodemailer from "nodemailer";

// Re-usable transporter. In dev we use MailDev (localhost:1025).
export const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST!,
  port: Number(process.env.SMTP_PORT || 25),
  secure: false, // MailDev does not use TLS
  auth:
    process.env.SMTP_USER && process.env.SMTP_PASS
      ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS }
      : undefined
});

/**
 * sendVerifyEmail - sends the verification link for registration.
 * Token is generated by auth route.
 */
export async function sendVerifyEmail(email: string, token: string) {
  const verifyUrl = `${process.env.BASE_URL}/verify?token=${encodeURIComponent(token)}`;
  await transporter.sendMail({
    from: process.env.MAIL_FROM!,
    to: email,
    subject: "Verify your Stego Trial account",
    text: `Please verify your account: ${verifyUrl}`,
    html: `Please verify your account: <a href="${verifyUrl}">${verifyUrl}</a>`
  });
}

/**
 * sendUploadReceipt - sends a short email after a file is scanned.
 */
export async function sendUploadReceipt(email: string, filename: string, verdict: string) {
  await transporter.sendMail({
    from: process.env.MAIL_FROM!,
    to: email,
    subject: "Your file was scanned",
    text: `File: ${filename}\nResult: ${verdict}`
  });
}
